name: DocC

on:
  push:
    branches: ["main", "develop" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build DocC
        run: |
          xcodebuild docbuild \
            -scheme BarKit \
            -destination 'generic/platform=iOS' \
            -derivedDataPath .build

      - name: Find doccarchive
        run: find .build -name "*.doccarchive"

      - name: Process for GitHub Pages
        run: |
          $(xcrun --find docc) process-archive transform-for-static-hosting \
            .build/Build/Products/Debug-iphoneos/BarKit.doccarchive \
            --output-path docs \
            --hosting-base-path BarKit

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          